export const site = {
  name: "GTSystems",
  legalName: "GTSystems I.T. Business Solutions",
  domain: "digital.gtsystems.gr",
  city: "Κέρκυρα",
  country: "Ελλάδα",
  address: "Κέρκυρα, Ελλάδα",
  registryNumber: "34476033000",
  phone: "+30 26617 00610",
  mobile: "+30 6945 971968",
  email: "info@gtsystems.gr",
  hours: "Δευτέρα - Παρασκευή: 9.00 - 17.00",
  founded: "2005",
  facebook: "https://www.facebook.com/GTSystemsIT",
  linkedin: "https://www.linkedin.com/company/gtsystems",
  logoWhite: "https://gtsystems.gr/gtswh.gif",
  logoBlack: "https://gtsystems.gr/gtsbh.gif",
  logo: "https://gtsystems.gr/gtsbh.gif",
  mark: "https://gtsystems.gr/wp-content/uploads/2021/09/gtsystemslogo60.png",
  socialImage: "https://gtsystems.gr/wp-content/uploads/2023/03/seo-social-image-gtsystems.gr_.png",
};

export const services = [
  {
    title: "Εμπορικό Λογισμικό",
    href: "/business-systems",
    image: "https://gtsystems.gr/wp-content/uploads/2019/01/megasoft-600x389.jpg",
    summary:
      "Εμπορικές, λογιστικές, λιανικής, εστίασης και reporting εφαρμογές, ρυθμισμένες γύρω από τον τρόπο λειτουργίας της επιχείρησής σας.",
    points: ["Εφαρμογές Megasoft", "Ροές εργασίας ERP", "Επιχειρησιακή πληροφόρηση"],
  },
  {
    title: "Ταμειακά & POS Συστήματα",
    href: "/business-systems#cash-pos",
    image: "https://gtsystems.gr/wp-content/uploads/2019/01/cashiers-600x389.jpg",
    summary:
      "Ταμειακές μηχανές, φορολογικοί μηχανισμοί, σύνδεση με ζυγιστικά, εγκατάσταση, εκπαίδευση και αξιόπιστη τοπική υποστήριξη.",
    points: ["Ταμειακά συστήματα", "Φορολογική συμμόρφωση", "Λιανική και εστίαση"],
  },
  {
    title: "Τεχνική Υποστήριξη",
    href: "/web-apps",
    image: "https://gtsystems.gr/wp-content/uploads/2019/01/support-600x389.jpg",
    summary:
      "Συμβόλαια υποστήριξης, service υπολογιστών και laptop, προμήθεια εξοπλισμού, ασφάλεια και πρακτική καθημερινή βοήθεια.",
    points: ["Συμβόλαια υποστήριξης", "Service εξοπλισμού", "Απομακρυσμένη βοήθεια"],
  },
  {
    title: "Δίκτυα & Υποδομές",
    href: "/web-development",
    image: "https://gtsystems.gr/wp-content/uploads/2019/01/networks-600x389.jpg",
    summary:
      "Ενσύρματα δίκτυα, κάλυψη Wi-Fi, τηλεφωνικά κέντρα, καλωδιώσεις και σχεδιασμός υποδομών για επαγγελματικούς χώρους.",
    points: ["Μελέτες Wi-Fi", "Δομημένη καλωδίωση", "Τηλεπικοινωνίες"],
  },
  {
    title: "Ιστοσελίδες & Web Apps",
    href: "/web-development",
    image: "https://gtsystems.gr/wp-content/uploads/2019/01/websites-600x389.jpg",
    summary:
      "Γρήγορες ιστοσελίδες, portals, dashboards και αυτοματισμοί που συνδέουν την online παρουσία με την καθημερινή λειτουργία.",
    points: ["Επαγγελματικές ιστοσελίδες", "Custom portals", "Αυτοματισμοί"],
  },
];

export const partnerLinks = [
  { label: "AnyDesk", href: "https://get.anydesk.com/" },
  { label: "Bitdefender GravityZone", href: "https://cloudgz.gravityzone.bitdefender.com/" },
];

export const providers = [
  {
    name: "Megasoft",
    category: "Business Software",
    product: "PRISMA Win",
    href: "https://megasoft.gr/",
    image: "https://gtsystems.gr/wp-content/uploads/2019/01/megasoft-600x389.jpg",
    logo: "https://megasoft.gr/images/logoMegasoftNew.png",
    tone: "Εμπορική διαχείριση, ηλεκτρονική τιμολόγηση, mobile workflows",
    description:
      "Το PRISMA Win καλύπτει την καθημερινή λειτουργία, την οργάνωση, τη διαχείριση πληροφορίας και τις φορολογικές εξελίξεις μιας επιχείρησης.",
    bullets: ["Εμπορική διαχείριση", "Ηλεκτρονική τιμολόγηση", "Πληροφορία σε πραγματικό χρόνο"],
  },
  {
    name: "RBS",
    category: "Retail & POS",
    product: "PEPPER All in One / NINE POS",
    href: "https://rbs.gr/",
    image: "https://rbs.gr/wp-content/uploads/2026/02/pepper-all-in-one-landing-pic-rbs-1-768x788.webp",
    logo: "https://rbs.gr/wp-content/uploads/2024/05/LOGO-RBS-TRANSP-scaled.png",
    tone: "Ταμειακή & POS σε μία συσκευή, εστίαση, λιανική, myDATA",
    description:
      "Η RBS καλύπτει συναλλαγές λιανικής και εστίασης με PEPPER All in One, NINE POS, EDASYS και σύγχρονα φορολογικά ταμειακά συστήματα.",
    bullets: ["PEPPER All in One", "NINE POS εστίασης", "Συμμόρφωση ΑΑΔΕ / myDATA"],
  },
  {
    name: "Bitdefender",
    category: "Cybersecurity",
    product: "GravityZone",
    href: "https://www.bitdefender.com/en-us/business/",
    image: "https://techzone.bitdefender.com/en/image/uuid-86e7b4f2-523c-2bc3-6d88-69d152f35250.jpg",
    logo: "",
    tone: "Endpoint protection, risk management, business security",
    description:
      "Το GravityZone φέρνει προστασία endpoint, πρόληψη απειλών και κεντρική εικόνα ασφάλειας για συσκευές, δίκτυα και cloud υπηρεσίες.",
    bullets: ["Business Security", "Threat prevention", "Endpoint visibility"],
  },
  {
    name: "AnyDesk",
    category: "Remote support",
    product: "Remote Support",
    href: "https://anydesk.com/en",
    image: "https://gtsystems.gr/wp-content/uploads/2019/01/support-600x389.jpg",
    logo: "",
    tone: "Remote support, device access, help desk workflows",
    description:
      "Το AnyDesk υποστηρίζει γρήγορη απομακρυσμένη βοήθεια, πρόσβαση σε συσκευές, mobile support και workflows τεχνικής υποστήριξης.",
    bullets: ["Remote Support", "Mobile device support", "Cloud ή on-premises"],
  },
];

export const websiteProjects = [
  {
    title: "OS Creations",
    category: "Κατάστημα",
    href: "https://gtsystems.gr/websites/os-creations/",
    website: "http://oscreations.art",
    image: "https://gtsystems.gr/wp-content/uploads/2023/02/oscreations-550x260.webp",
  },
  {
    title: "AMR Greece",
    category: "Ξενοδοχεία",
    href: "https://gtsystems.gr/websites/amr-greece/",
    website: "https://www.amresortseu.gr",
    image: "https://gtsystems.gr/wp-content/uploads/2023/02/amresortsgr-550x260.webp",
  },
  {
    title: "Corfu Delicatessen",
    category: "Κατάστημα",
    href: "https://gtsystems.gr/websites/corfu-delicatessen/",
    website: "http://corfudelicatessen.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2023/02/corfudelicatessen-550x260.webp",
  },
  {
    title: "Auto Plan Corfu",
    category: "Κατάστημα",
    href: "https://gtsystems.gr/websites/auto-plan-corfu/",
    website: "https://autoplancorfu.gr/",
    image: "https://gtsystems.gr/wp-content/uploads/2023/02/autoplancorfu-550x260.webp",
  },
  {
    title: "Diamond Luxury Villa Corfu",
    category: "Ξενοδοχεία",
    href: "https://gtsystems.gr/websites/diamond-luxury-villa-corfu/",
    website: "https://www.luxuryvilladiamondcorfu.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2023/02/luxuryvilladiamondcorfu-550x260.webp",
  },
  {
    title: "Golden Home Corfu",
    category: "Υπηρεσίες",
    href: "https://gtsystems.gr/websites/golden-home-corfu/",
    website: "https://www.goldenhomecorfu.com",
    image: "https://gtsystems.gr/wp-content/uploads/2021/09/goldenhomecorfu-550x260.webp",
  },
  {
    title: "Angel Transfers Corfu",
    category: "Υπηρεσίες",
    href: "https://gtsystems.gr/websites/angel-transfers-corfu/",
    website: "https://www.angeltransferscorfu.com",
    image: "https://gtsystems.gr/wp-content/uploads/2021/09/angel-transfers-corfu-1-550x260.jpg",
  },
  {
    title: "S & C Kosmos Beach Resort",
    category: "Ξενοδοχεία",
    href: "https://gtsystems.gr/websites/s-c-kosmos-beach-resort/",
    website: "https://sckosmos.com",
    image: "https://gtsystems.gr/wp-content/uploads/2021/09/sc-kosmos-beach-resort-550x260.jpg",
  },
  {
    title: "Serena Hotel",
    category: "Ξενοδοχεία",
    href: "https://gtsystems.gr/websites/serena-hotel/",
    website: "https://serena.gr/",
    image: "https://gtsystems.gr/wp-content/uploads/2021/09/serena-hotel-550x260.jpg",
  },
  {
    title: "Marina Boutique Hotel",
    category: "Ξενοδοχεία",
    href: "https://gtsystems.gr/websites/marina-boutique-hotel/",
    website: "https://marinahotelcorfu.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/marina-boutique-hotel-550x260.jpg",
  },
  {
    title: "Moraitika Tourist Agency",
    category: "Υπηρεσίες",
    href: "https://gtsystems.gr/websites/moraitika-tourist-agency/",
    website: "https://www.gstouristcentre.gr/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/moraitika-tourist-agency-550x260.jpg",
  },
  {
    title: "Vintage Village House",
    category: "Καταλύματα",
    href: "https://gtsystems.gr/websites/vintage-village-house/",
    website: "https://vintagevillagehouse.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/vintage-village-house-550x260.jpg",
  },
  {
    title: "Villa Sun Mare",
    category: "Καταλύματα",
    href: "https://gtsystems.gr/websites/villa-sun-mare/",
    website: "https://villasunmare.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/villa-sun-mare-550x260.jpg",
  },
  {
    title: "Captain Homer's Boat Trips",
    category: "Υπηρεσίες",
    href: "https://gtsystems.gr/websites/captain-homers-boat-trips/",
    website: "https://captainhomersboattrips.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/captain-homers-boat-trips-1-550x260.jpg",
  },
  {
    title: "Palidou",
    category: "Κατάστημα",
    href: "https://gtsystems.gr/websites/palidou/",
    website: "https://palidou.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/palidou-550x260.jpg",
  },
  {
    title: "Nivosoap",
    category: "Κατάστημα",
    href: "https://gtsystems.gr/websites/nivosoap/",
    website: "https://www.nivosoap.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/nivosoap-1-550x260.jpg",
  },
  {
    title: "Villa Mediterranean View",
    category: "Καταλύματα",
    href: "https://gtsystems.gr/websites/villa-mediterranean-view/",
    website: "https://villamediterraneanview.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/villa-mediterranean-view-1-550x260.jpg",
  },
  {
    title: "Privilege Speed Boats",
    category: "Υπηρεσίες",
    href: "https://gtsystems.gr/websites/privilege-speed-boats/",
    website: "http://privilegespeedboats.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/privilege-speed-boats-550x260.jpg",
  },
  {
    title: "Stefanos Resort",
    category: "Καταλύματα",
    href: "https://gtsystems.gr/websites/stefanos-resort/",
    website: "https://stefanosresort.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/stefanos-resort-550x260.jpg",
  },
  {
    title: "South Corfu Runners",
    category: "Υπηρεσίες",
    href: "https://gtsystems.gr/websites/south-corfu-runners/",
    website: "https://southcorfurunners.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/southcorfurunners-550x260.webp",
  },
  {
    title: "Villa Ramos",
    category: "Καταλύματα",
    href: "https://gtsystems.gr/websites/villa-ramos/",
    website: "https://villa-ramos.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/villa-ramos-550x260.jpg",
  },
  {
    title: "ELAEON",
    category: "Κατάστημα",
    href: "https://gtsystems.gr/websites/el%e2%a8%81aeon/",
    website: "https://www.corfuelaeon.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/elaeon-550x260.jpg",
  },
  {
    title: "ME.LIFE Studio Pilates",
    category: "Υπηρεσίες",
    href: "https://gtsystems.gr/websites/me-life-studio-pilates/",
    website: "https://melife.fitness/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/melife-studio-pilates.-550x260.jpg",
  },
  {
    title: "Corfu 3 Stars Villas",
    category: "Καταλύματα",
    href: "https://gtsystems.gr/websites/corfu-3-stars-villas/",
    website: "https://corfu3starsvillas.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/corfu3stars-villas-550x260.jpg",
  },
  {
    title: "75 Steps Taverna & Accommodation",
    category: "Καταλύματα",
    href: "https://gtsystems.gr/websites/75-steps-taverna-accomodation/",
    website: "https://75steps.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/75steps-550x260.jpg",
  },
  {
    title: "WiFi HotSpot",
    category: "Υπηρεσίες",
    href: "https://gtsystems.gr/websites/wifi-hotspot/",
    website: "https://wifihotspot.gr/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/wifi-hotspot-550x260.jpg",
  },
  {
    title: "Nektarios Chanos Accounting & Tax Services",
    category: "Υπηρεσίες",
    href: "https://gtsystems.gr/websites/nektarios-chanos-accounting-tax-services/",
    website: "https://ntsanos.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/ntsanos-550x260.jpg",
  },
  {
    title: "Villa Panorea",
    category: "Καταλύματα",
    href: "https://gtsystems.gr/websites/villa-panorea/",
    website: "https://villapanorea.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/villa-panorea-550x260.jpg",
  },
  {
    title: "Balis Cafe Taverna",
    category: "Καφέ - Εστιατόρια",
    href: "https://gtsystems.gr/websites/balis-cafe-taverna/",
    website: "https://corfu-balis.gr/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/balis-cafe-taverna-550x260.jpg",
  },
  {
    title: "Stars Hotel",
    category: "Ξενοδοχεία",
    href: "https://gtsystems.gr/websites/stars-hotel/",
    website: "https://corfustars.gr/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/stars-hotel-550x260.jpg",
  },
  {
    title: "Corfu Properties South",
    category: "Υπηρεσίες",
    href: "https://gtsystems.gr/websites/corfu-properties-south/",
    website: "http://corfupropertiessouth.gr",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/corfupropertiessouth-550x260.webp",
  },
  {
    title: "Lina's Studios",
    category: "Καταλύματα",
    href: "https://gtsystems.gr/websites/linas-studios/",
    website: "http://linastudios.com/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/linastudios-550x260.webp",
  },
  {
    title: "Tsoupi's Villa",
    category: "Καταλύματα",
    href: "https://gtsystems.gr/websites/tsoupis-villa/",
    website: "http://tsoupisvilla.com",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/tsoupisvilla-550x260.webp",
  },
  {
    title: "Tasia Studios",
    category: "Καταλύματα",
    href: "https://gtsystems.gr/websites/tasia-studios/",
    website: "https://corfu-tasia-studios.gr/",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/corfu-tasia-studios-550x260.webp",
  },
  {
    title: "Miami Seaview",
    category: "Καταλύματα",
    href: "https://gtsystems.gr/websites/miami-seaview/",
    website: "http://miamiseaview.gr",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/miamiseaview-550x260.webp",
  },
  {
    title: "Go Zaxos",
    category: "Υπηρεσίες",
    href: "https://gtsystems.gr/websites/go-zaxos/",
    website: "http://gozaxos.gr",
    image: "https://gtsystems.gr/wp-content/uploads/2020/10/gozaxos-550x260.webp",
  },
];
